### ISSUE TITLE
Feedback for “MongoDB Community Server”

### ISSUE THREAD

**Issue by felixthekraut** [LibreChat-AI/librechat.ai#27]
I believe that this page needs to be updated, but I am not 100% sure. It appears that the `MONGO_URI` is specified in `docker-compose.yml` and is not overridden when setting it in `.env`. 

At least for me I had to add an override in `docker-compose.override.yml` as follows:
```
services:
  api:
    environment:
    - MONGO_URI=mongodb://user:pass@host1:27017,host2:27017,host3:27017/LibreChat?authSource=admin&replicaSet=setname
```
