### ISSUE TITLE
Feedback for “Agents Endpoint Object Structure”

### ISSUE THREAD

**Issue by onknows** [LibreChat-AI/librechat.ai#277]
I tried various options related to agents builder but it consistently produces this error. Now the behavior is that when a user clicks on the Agent Builder in the top right corner this will break the LibreChat. LibreChat will no longer function and the user is required to clear the browser cache to get it working again. It tried configuration below in `librechat.yaml`.  With `disableBuilder: false` and `disableBuilder: true`. The Agent Builder however is always present in the top right corner as a direct way to break LibreChat. Is there a way to remove the Agent Build in the top right corner?

> Error Message:
> 
> a.capabilities is undefined

```yaml
endpoints:
  agents:
    recursionLimit: 50
    maxRecursionLimit: 100
    disableBuilder: false
    capabilities:
      - "execute_code"
      - "file_search"
      - "actions"
      - "tools"
      - "artifacts"
      - "ocr"
      - "chain"
```

![Image](https://github.com/user-attachments/assets/087c9b2d-a6e0-42f6-b62a-a9788fd872d3)
